name: Setup Spacectl
author: Spacelift
description: |
  This action installs the Spacectl CLI tool and
  adds it to the PATH.

inputs:
  version:
    description: The version of Spacectl to install. Defaults to latest.
    default: latest
  github-token:
    description: GitHub token to use for querying the GitHub API.
    required: false
    default: ${{ github.token }}

runs:
  using: node20
  main: dist/index.js
