name: check dist

on:
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  check-dist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install packages
        run: npm ci

      - name: Check if JavaScript is compiled
        run: |
          npm run build
          git diff --name-only --exit-code dist/
